# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pascal/Documents/Uni/POOSE/poose3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pascal/Documents/Uni/POOSE/poose3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pascal/Documents/Uni/POOSE/poose3/CMakeFiles /home/pascal/Documents/Uni/POOSE/poose3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pascal/Documents/Uni/POOSE/poose3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server_module

# Build rule for target.
server_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_module
.PHONY : server_module

# fast build rule for target.
server_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/build
.PHONY : server_module/fast

#=============================================================================
# Target rules for targets named demo1

# Build rule for target.
demo1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo1
.PHONY : demo1

# fast build rule for target.
demo1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/build
.PHONY : demo1/fast

#=============================================================================
# Target rules for targets named demo2

# Build rule for target.
demo2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo2
.PHONY : demo2

# fast build rule for target.
demo2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/build
.PHONY : demo2/fast

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

demo/demo1.o: demo/demo1.cpp.o
.PHONY : demo/demo1.o

# target to build an object file
demo/demo1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/demo/demo1.cpp.o
.PHONY : demo/demo1.cpp.o

demo/demo1.i: demo/demo1.cpp.i
.PHONY : demo/demo1.i

# target to preprocess a source file
demo/demo1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/demo/demo1.cpp.i
.PHONY : demo/demo1.cpp.i

demo/demo1.s: demo/demo1.cpp.s
.PHONY : demo/demo1.s

# target to generate assembly for a file
demo/demo1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/demo/demo1.cpp.s
.PHONY : demo/demo1.cpp.s

demo/demo2.o: demo/demo2.cpp.o
.PHONY : demo/demo2.o

# target to build an object file
demo/demo2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/demo/demo2.cpp.o
.PHONY : demo/demo2.cpp.o

demo/demo2.i: demo/demo2.cpp.i
.PHONY : demo/demo2.i

# target to preprocess a source file
demo/demo2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/demo/demo2.cpp.i
.PHONY : demo/demo2.cpp.i

demo/demo2.s: demo/demo2.cpp.s
.PHONY : demo/demo2.s

# target to generate assembly for a file
demo/demo2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/demo/demo2.cpp.s
.PHONY : demo/demo2.cpp.s

server/pybind.o: server/pybind.cpp.o
.PHONY : server/pybind.o

# target to build an object file
server/pybind.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/server/pybind.cpp.o
.PHONY : server/pybind.cpp.o

server/pybind.i: server/pybind.cpp.i
.PHONY : server/pybind.i

# target to preprocess a source file
server/pybind.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/server/pybind.cpp.i
.PHONY : server/pybind.cpp.i

server/pybind.s: server/pybind.cpp.s
.PHONY : server/pybind.s

# target to generate assembly for a file
server/pybind.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/server/pybind.cpp.s
.PHONY : server/pybind.cpp.s

src/Product.o: src/Product.cpp.o
.PHONY : src/Product.o

# target to build an object file
src/Product.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/Product.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/Product.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/Product.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/Product.cpp.o
.PHONY : src/Product.cpp.o

src/Product.i: src/Product.cpp.i
.PHONY : src/Product.i

# target to preprocess a source file
src/Product.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/Product.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/Product.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/Product.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/Product.cpp.i
.PHONY : src/Product.cpp.i

src/Product.s: src/Product.cpp.s
.PHONY : src/Product.s

# target to generate assembly for a file
src/Product.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/Product.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/Product.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/Product.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/Product.cpp.s
.PHONY : src/Product.cpp.s

src/Server.o: src/Server.cpp.o
.PHONY : src/Server.o

# target to build an object file
src/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/Server.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/Server.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/Server.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/Server.cpp.o
.PHONY : src/Server.cpp.o

src/Server.i: src/Server.cpp.i
.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/Server.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/Server.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/Server.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/Server.cpp.i
.PHONY : src/Server.cpp.i

src/Server.s: src/Server.cpp.s
.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/Server.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/Server.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/Server.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/Server.cpp.s
.PHONY : src/Server.cpp.s

src/User.o: src/User.cpp.o
.PHONY : src/User.o

# target to build an object file
src/User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/User.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/User.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/User.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/User.cpp.o
.PHONY : src/User.cpp.o

src/User.i: src/User.cpp.i
.PHONY : src/User.i

# target to preprocess a source file
src/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/User.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/User.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/User.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/User.cpp.i
.PHONY : src/User.cpp.i

src/User.s: src/User.cpp.s
.PHONY : src/User.s

# target to generate assembly for a file
src/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server_module.dir/build.make CMakeFiles/server_module.dir/src/User.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo1.dir/build.make CMakeFiles/demo1.dir/src/User.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo2.dir/build.make CMakeFiles/demo2.dir/src/User.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/User.cpp.s
.PHONY : src/User.cpp.s

tests/unittests.o: tests/unittests.cpp.o
.PHONY : tests/unittests.o

# target to build an object file
tests/unittests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/tests/unittests.cpp.o
.PHONY : tests/unittests.cpp.o

tests/unittests.i: tests/unittests.cpp.i
.PHONY : tests/unittests.i

# target to preprocess a source file
tests/unittests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/tests/unittests.cpp.i
.PHONY : tests/unittests.cpp.i

tests/unittests.s: tests/unittests.cpp.s
.PHONY : tests/unittests.s

# target to generate assembly for a file
tests/unittests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/tests/unittests.cpp.s
.PHONY : tests/unittests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... demo1"
	@echo "... demo2"
	@echo "... server_module"
	@echo "... unittests"
	@echo "... demo/demo1.o"
	@echo "... demo/demo1.i"
	@echo "... demo/demo1.s"
	@echo "... demo/demo2.o"
	@echo "... demo/demo2.i"
	@echo "... demo/demo2.s"
	@echo "... server/pybind.o"
	@echo "... server/pybind.i"
	@echo "... server/pybind.s"
	@echo "... src/Product.o"
	@echo "... src/Product.i"
	@echo "... src/Product.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
	@echo "... src/User.o"
	@echo "... src/User.i"
	@echo "... src/User.s"
	@echo "... tests/unittests.o"
	@echo "... tests/unittests.i"
	@echo "... tests/unittests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

