[project]
name = "poose03"
version = "0.1.0"
description = "Mercatori"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115",
    "uvicorn>=0.34",
    "pybind11",
    "requests>=2.32.4",
    "pyqt6>=6.9.1",
    "matplotlib>=3.10.3",
    "websockets"
]
